version: "3"
services:
  backend:
    env_file:
      - env.env
    build: ./back-end
    ports: 
      - "2000:1337"
    links: 
      - mongo
  quote-of-the-day:
    env_file:
      - env.env
    build: ./quote-of-the-day
    ports: 
      - "2001:1338"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db_smecherzzz
    ports:
      - "27017:27017"